spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oniichan?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
     database: MYSQL
     hibernate:
        ddl-auto: update
     show-sql: false
     properties:
        hibernate:
           dialect: org.hibernate.dialect.MySQL5InnoDBDialect
           globally_quoted_identifiers: true